####################################################################################################
# +----------------------------------------------------------------------------------------------+ #
# |                         █████▒     █  █░    █  █░ ▄▄▄      ██▀███                            | #
# |                         ▓██   ▒▓█░ █ ░█░▓█░ █ ░█░▒████▄    ▓██ ▒ ██▒                         | #
# |                         ▒████ ░▒█░ █ ░█ ▒█░ █ ░█ ▒██  ▀█▄  ▓██ ░▄█ ▒                         | #
# |                         ░▓█▒  ░░█░ █ ░█ ░█░ █ ░█ ░██▄▄▄▄██ ▒██▀▀█▄                           | #
# |                         ░▒█░   ░░██▒██▓ ░░██▒██▓  ▓█   ▓██▒░██▓ ▒██▒                         | #
# |                         ▒ ░   ░ ▓░▒ ▒  ░ ▓░▒ ▒   ▒▒   ▓▒█░░ ▒▓ ░▒▓░                          | #
# |                         ░       ▒ ░ ░    ▒ ░ ░    ▒   ▒▒ ░  ░▒ ░ ▒░                          | #
# |                         ░ ░     ░   ░    ░   ░    ░   ▒     ░░   ░                           | #
# |                         ░        ░          ░  ░   ░                                         | #
# |                                                                                              | #
# |                                     Made by: Kaotich00                                       | #
# |                                                                                              | #
# |                    SOURCE CODE: https://github.com/ForgottenWorld/FwWar                      | #
# |                                                                                              | #
# +----------------------------------------------------------------------------------------------+ #
####################################################################################################
